version: "3.9"
services:
  transform:
    image: molgenis/molgenis-py-catalogue-transform:latest
    environment:
      - MG_CATALOGUE_NETWORKS=LifeCycle, ATHLETE, LongITools
      - MG_CATALOGUE_COHORTS=NFBC1966, NFBC1986, KANC
      - MG_CATALOGUE_URL_STAGING=https://data-catalogue-staging.molgeniscloud.org/
      - MG_CATALOGUE_USERNAME_STAGING=admin
      - MG_CATALOGUE_PASSWORD_STAGING=
      - MG_CATALOGUE_URL_PROD=https://emx2.test.molgenis.org/
      - MG_CATALOGUE_USERNAME_PROD=admin
      - MG_CATALOGUE_PASSWORD_PROD=